## REVENUE TREND ANALYSIS

## STEP 1- Import libraries and load dataset

In [47]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_csv("Statistics_dataset_uncleaned.csv")

In [49]:
df.head()

,Record_ID,Month_Number,Month_Date,Phase,Customer_ID,Industry,Region,Plan_Type,Acquisition_Channel,Seats,Customer_Status,MRR_Amount,Total_Company_MRR,Active_Customer_Count
0,1,1,2019-01-01,Phase 1 - Startup,CUST-00001,Management Consulting,APAC,Starter,Outbound Sales,4.0,New,86.64,5200.0,8
1,2,1,2019-01-01,Phase 1 - Startup,CUST-00002,Real Estate Services,India,Starter,Paid Ads,5.0,New,92.10,5200.0,8
2,3,1,2019-01-01,Phase 1 - Startup,CUST-00003,Marketing & Advertising Agency,APAC,Starter,Referral,5.0,New,226.66,5200.0,8
3,4,1,2019-01-01,Phase 1 - Startup,CUST-00004,Media Production,India,Growth,Outbound Sales,20.0,New,335.82,5200.0,8
4,5,1,2019-01-01,Phase 1 - Startup,CUST-00006,Architecture & Design Studio,Middle East,Starter,Content Marketing,5.0,New,178.86,5200.0,8

In [50]:
df.shape

(5012, 14)

In [51]:
df.columns

Index(['Record_ID', 'Month_Number', 'Month_Date', 'Phase', 'Customer_ID',
       'Industry', 'Region', 'Plan_Type', 'Acquisition_Channel', 'Seats',
       'Customer_Status', 'MRR_Amount', 'Total_Company_MRR',
       'Active_Customer_Count'],
      dtype='object')

In [52]:
df.dtypes

Record_ID                  int64
Month_Number               int64
Month_Date                object
Phase                     object
Customer_ID               object
Industry                  object
Region                    object
Plan_Type                 object
Acquisition_Channel       object
Seats                    float64
Customer_Status           object
MRR_Amount               float64
Total_Company_MRR        float64
Active_Customer_Count      int64
dtype: object

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5012 entries, 0 to 5011
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Record_ID              5012 non-null   int64
 1   Month_Number           5012 non-null   int64
 2   Month_Date             5012 non-null   object
 3   Phase                  5012 non-null   object
 4   Customer_ID            5012 non-null   object
 5   Industry               5012 non-null   object
 6   Region                 4987 non-null   object
 7   Plan_Type              4992 non-null   object
 8   Acquisition_Channel    4997 non-null   object
 9   Seats                  4997 non-null   float64
 10  Customer_Status        5012 non-null   object
 11  MRR_Amount             4997 non-null   float64
 12  Total_Company_MRR      5012 non-null   float64
 13  Active_Customer_Count  5012 non-null   int64
dtypes: float64(3), int64(3), object(8)
memory usage: 548.3+ KB

In [54]:
df.describe()

,Record_ID,Month_Number,Seats,MRR_Amount,Total_Company_MRR,Active_Customer_Count
count,5012.000000,5012.000000,4997.000000,4997.000000,5012.000000,5012.000000
mean,2500.626297,58.855547,23.581549,1395.559644,127013.529250,90.911612
std,1443.151367,19.520716,31.664095,2232.574356,51455.907884,38.606416
min,1.000000,1.000000,-113.000000,-1658.730000,5200.000000,8.000000
25%,1250.750000,46.000000,5.000000,218.400000,85686.340000,60.000000
50%,2499.500000,63.000000,11.000000,545.070000,144437.150000,95.000000
75%,3749.250000,75.000000,25.000000,1521.830000,172794.830000,124.000000
max,5000.000000,84.000000,148.000000,22087.380000,187678.310000,148.000000

In [55]:
df.describe(include="object")

,Month_Date,Phase,Customer_ID,Industry,Region,Plan_Type,Acquisition_Channel,Customer_Status
count,5012,5012,5012,5012,4987,4992,4997,5012
unique,103,3,339,17,14,11,10,12
top,2025-12-01,Phase 3 - Maturation,CUST-00007,Marketing & Advertising Agency,India,Starter,Referral,Existing
freq,148,2741,83,1142,1749,2131,1363,3841

## STEP 2 DATA CLEANING

In [56]:
df.isnull().sum()

Record_ID                 0
Month_Number              0
Month_Date                0
Phase                     0
Customer_ID               0
Industry                  0
Region                   25
Plan_Type                20
Acquisition_Channel      15
Seats                    15
Customer_Status           0
MRR_Amount               15
Total_Company_MRR         0
Active_Customer_Count     0
dtype: int64

In [57]:
df.isnull().sum() / len(df)*100

Record_ID                0.000000
Month_Number             0.000000
Month_Date               0.000000
Phase                    0.000000
Customer_ID              0.000000
Industry                 0.000000
Region                   0.498803
Plan_Type                0.399042
Acquisition_Channel      0.299282
Seats                    0.299282
Customer_Status          0.000000
MRR_Amount               0.299282
Total_Company_MRR        0.000000
Active_Customer_Count    0.000000
dtype: float64

In [58]:
df['Region'] = df['Region'].fillna(df['Region'].mode()[0])

df['Plan_Type'] = df['Plan_Type'].fillna(df['Plan_Type'].mode()[0])

df['Acquisition_Channel'] = df['Acquisition_Channel'].fillna(
    df['Acquisition_Channel'].mode()[0]
)

In [59]:
df['Seats'] = df['Seats'].fillna(df['Seats'].median())

df['MRR_Amount'] = df['MRR_Amount'].fillna(df['MRR_Amount'].median())

In [60]:
df.isnull().sum()

Record_ID                0
Month_Number             0
Month_Date               0
Phase                    0
Customer_ID              0
Industry                 0
Region                   0
Plan_Type                0
Acquisition_Channel      0
Seats                    0
Customer_Status          0
MRR_Amount               0
Total_Company_MRR        0
Active_Customer_Count    0
dtype: int64

In [61]:
df.duplicated().sum()

np.int64(11)

In [62]:
df = df.drop_duplicates()

In [63]:
df.duplicated().sum()

np.int64(0)

In [64]:
df.dtypes

Record_ID                  int64
Month_Number               int64
Month_Date                object
Phase                     object
Customer_ID               object
Industry                  object
Region                    object
Plan_Type                 object
Acquisition_Channel       object
Seats                    float64
Customer_Status           object
MRR_Amount               float64
Total_Company_MRR        float64
Active_Customer_Count      int64
dtype: object

In [65]:
df["Month_Number"] = pd.to_numeric(df["Month_Number"], errors="coerce")
df["Seats"] = pd.to_numeric(df["Seats"], errors="coerce")
df["MRR_Amount"] = pd.to_numeric(df["MRR_Amount"], errors="coerce")
df["Total_Company_MRR"] = pd.to_numeric(df["Total_Company_MRR"], errors="coerce")
df["Active_Customer_Count"] = pd.to_numeric(df["Active_Customer_Count"], errors="coerce")

In [66]:
df.dtypes

Record_ID                  int64
Month_Number               int64
Month_Date                object
Phase                     object
Customer_ID               object
Industry                  object
Region                    object
Plan_Type                 object
Acquisition_Channel       object
Seats                    float64
Customer_Status           object
MRR_Amount               float64
Total_Company_MRR        float64
Active_Customer_Count      int64
dtype: object

In [67]:
df["Region"] = df["Region"].str.strip()
df["Industry"] = df["Industry"].str.strip()
df["Plan_Type"] = df["Plan_Type"].str.strip()
df["Acquisition_Channel"] = df["Acquisition_Channel"].str.strip()
df["Customer_Status"] = df["Customer_Status"].str.strip()
df["Phase"] = df["Phase"].str.strip()

In [68]:
df["Region"].unique()

array(['APAC', 'India', 'Middle East', 'Europe', 'North America', 'south',
       'North', 'South', 'NORTH', 'West', 'EAST'], dtype=object)

In [69]:
df["Plan_Type"].unique()

array(['Starter', 'Growth', 'Enterprise', 'enterprise', 'basic', 'BASIC',
       'Pro', 'ENTERPRISE'], dtype=object)

In [70]:
df["Customer_Status"].unique()

array(['New', 'Existing', 'Contraction', 'Expansion', 'Churned',
       'churned', 'active', 'ACTIVE'], dtype=object)

In [71]:
df["Region"] = df["Region"].str.title()
df["Plan_Type"] = df["Plan_Type"].str.title()
df["Customer_Status"] = df["Customer_Status"].str.title()

In [72]:
df["Region"].unique()

array(['Apac', 'India', 'Middle East', 'Europe', 'North America', 'South',
       'North', 'West', 'East'], dtype=object)

In [73]:
(df["Seats"] < 0).sum()

np.int64(5)

In [74]:
(df["MRR_Amount"] < 0).sum()

np.int64(4)

In [75]:
(df["Total_Company_MRR"] < 0).sum()

np.int64(0)

In [76]:
df.loc[df["Seats"] < 0, "Seats"] = np.nan
df.loc[df["MRR_Amount"] < 0, "MRR_Amount"] = np.nan
df.loc[df["Total_Company_MRR"] < 0, "Total_Company_MRR"] = np.nan

In [77]:
df.isnull().sum()

Record_ID                0
Month_Number             0
Month_Date               0
Phase                    0
Customer_ID              0
Industry                 0
Region                   0
Plan_Type                0
Acquisition_Channel      0
Seats                    5
Customer_Status          0
MRR_Amount               4
Total_Company_MRR        0
Active_Customer_Count    0
dtype: int64

In [78]:
df["Seats"] = df["Seats"].fillna(df["Seats"].median())

df["MRR_Amount"] = df["MRR_Amount"].fillna(df["MRR_Amount"].median())

df["Total_Company_MRR"] = df["Total_Company_MRR"].fillna(
    df["Total_Company_MRR"].median()
)

In [79]:
df.isnull().sum()
##df[df["Month_Date"].isna()]

Record_ID                0
Month_Number             0
Month_Date               0
Phase                    0
Customer_ID              0
Industry                 0
Region                   0
Plan_Type                0
Acquisition_Channel      0
Seats                    0
Customer_Status          0
MRR_Amount               0
Total_Company_MRR        0
Active_Customer_Count    0
dtype: int64

In [80]:
df["Month_Date"] = pd.to_datetime(df["Month_Date"], errors="coerce")

df["Month_Date"] = df.groupby("Month_Number")["Month_Date"].transform("first")

In [81]:
df["Month_Date"].isnull().sum()

np.int64(0)

In [85]:
# Check actual duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 1

In [86]:
# Show the duplicate row
df[df.duplicated(keep=False)]

,Record_ID,Month_Number,Month_Date,Phase,Customer_ID,Industry,Region,Plan_Type,Acquisition_Channel,Seats,Customer_Status,MRR_Amount,Total_Company_MRR,Active_Customer_Count
2477,2478,63,2024-03-01,Phase 3 - Maturation,CUST-00073,Architecture & Design Studio,India,Growth,Paid Ads,11.0,Existing,1803.26,144437.15,95
5001,2478,63,2024-03-01,Phase 3 - Maturation,CUST-00073,Architecture & Design Studio,India,Growth,Paid Ads,11.0,Existing,1803.26,144437.15,95

In [87]:
df = df.drop_duplicates()

## STEP 3 FINAL QUALITY CHECK

In [88]:
df.shape

(5000, 14)

In [89]:
df.isnull().sum()

Record_ID                0
Month_Number             0
Month_Date               0
Phase                    0
Customer_ID              0
Industry                 0
Region                   0
Plan_Type                0
Acquisition_Channel      0
Seats                    0
Customer_Status          0
MRR_Amount               0
Total_Company_MRR        0
Active_Customer_Count    0
dtype: int64

In [90]:
df.duplicated().sum()

np.int64(0)

In [91]:
df.dtypes

Record_ID                         int64
Month_Number                      int64
Month_Date               datetime64[ns]
Phase                            object
Customer_ID                      object
Industry                         object
Region                           object
Plan_Type                        object
Acquisition_Channel              object
Seats                           float64
Customer_Status                  object
MRR_Amount                      float64
Total_Company_MRR               float64
Active_Customer_Count             int64
dtype: object

In [92]:
df.describe()

,Record_ID,Month_Number,Month_Date,Seats,MRR_Amount,Total_Company_MRR,Active_Customer_Count
count,5000.000000,5000.000000,5000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,58.850400,2023-10-27 07:21:30.239999744,23.589800,1393.520306,126997.923346,90.904800
min,1.000000,1.000000,2019-01-01 00:00:00,2.000000,0.000000,5200.000000,8.000000
25%,1250.750000,46.000000,2022-10-01 00:00:00,5.000000,219.112500,85686.340000,60.000000
50%,2500.500000,63.000000,2024-03-01 00:00:00,11.000000,545.070000,144437.150000,95.000000
75%,3750.250000,75.000000,2025-03-01 00:00:00,25.000000,1514.645000,172794.830000,124.000000
max,5000.000000,84.000000,2025-12-01 00:00:00,148.000000,22087.380000,187678.310000,148.000000
std,1443.520003,19.529636,NaN,31.581124,2230.805255,51474.050690,38.619249

In [93]:
df.to_csv("Trend_Analysis_dataset.csv", index=False)
print("DATASET SAVED SUCCESSFULLY")

DATASET SAVED SUCCESSFULLY